# Generated by Django 3.0.8 on 2020-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('First_name', models.CharField(default='', max_length=50)),
                ('Last_name', models.CharField(default='', max_length=50)),
                ('Aadhar_number', models.IntegerField()),
                ('Email_Address', models.EmailField(default='', max_length=254)),
                ('Contact_Number', models.PositiveIntegerField()),
            ],
        ),
    ]
